### ISSUE TITLE
puppet not starting at Running /docker-entrypoint.d/90-ca.sh

### ISSUE THREAD

**Issue by jsfrerot** [voxpupuli/container-puppetserver#88]
Hi, I'm not able to restart puppet server at this moment. Not sure what happened, I thought it was able to restart after the initial start, but today I can't restart it.
```
puppet_1       | Running /docker-entrypoint.d/90-ca.sh
puppet_1       | Error:
puppet_1       | Existing file at '/etc/puppetlabs/puppet/ssl/certs/puppet.mydomain.io.pem'
puppet_1       | Existing file at '/etc/puppetlabs/puppet/ssl/certs/ca.pem'
puppet_1       | Existing file at '/etc/puppetlabs/puppet/ssl/crl.pem'
puppet_1       | If you would really like to replace your CA, please delete the existing files first.
puppet_1       | Note that any certificates that were issued by this CA will become invalid if you
puppet_1       | replace it!
docker_puppet_1 exited with code 1
```

I'm using docker-compose and here is the configuration
```
  puppet:
    restart: "no"
    hostname: puppet.${DOMAIN:-internal}
    image: voxpupuli/container-puppetserver:8.6.0-main
    ports:
      - 8140:8140
    environment:
      - CA_ALLOW_SUBJECT_ALT_NAMES=true
      - PUPPETSERVER_HOSTNAME=puppet.${DOMAIN:-internal}
      - DNS_ALT_NAMES=puppet,puppet.${DOMAIN:-internal},${DNS_ALT_NAMES:-}
      - PUPPERWARE_ANALYTICS_ENABLED=${PUPPERWARE_ANALYTICS_ENABLED:-true}
      - PUPPETDB_SERVER_URLS=https://puppetdb.${DOMAIN:-internal}:8081
    volumes:
      - ${VOLUME_ROOT:-.}/volumes/code:/etc/puppetlabs/code/
      - ${VOLUME_ROOT:-.}/volumes/puppet:/etc/puppetlabs/puppet/
      - ${VOLUME_ROOT:-.}/volumes/serverdata:/opt/puppetlabs/server/data/puppetserver/
    dns_search: ${DOMAIN:-internal}
    networks:
      default:
        aliases:
         - puppet.${DOMAIN:-internal}
```
and my env file in  /etc/docker/.env 
```
VOLUME_ROOT=/opt/data/docker-compose/
DOMAIN=mydomain.io
DNS_ALT_NAMES=bln-puppet-001.mydomain.io
```
any idea of what is happenning?

Thank you.
